Depinstall through serialized spec.yaml
cosunae/spack-mch pull request #3
Opened 2021-04-14 11:25 UTC by Stagno

Using this spec.yaml for testing purposes (it's not intended to be final): https://github.com/cosunae/cosmo/pull/4

This is just a draft: I adapted `devbuildcosmo.py` to use spack's yaml format of specs instead of the custom `DepsYamlConf` to retrieve the dependencies' versions.
I'm not sure this draft satisfies all the requirements, for example I'm not sure about how exactly the following entries of `dependencies.yaml` were interpreted:
```
package: cosmo
version_from_git: "false"
tag: 5.08.mch1.0.base
cosmo-dycore: 5.08.mch1.0.base
```
Clearly the draft lacks the analogous changes to `depinstallcosmo.py`, but those should be trivial to apply once the doubts are solved.

2021-04-16 07:55 UTC, cosunae commented
some info about yaml:
`package: cosmo` -> just to identify the package, in case these yamls would end up in a workflows out of the repo. But we if aim putting it in the repo (in order to associate it with the tag) this is probably not needed. 
`version_from_git: "false"` -> this was a first attempt to solve the problem of associating the dycore version with cosmo version. What this was doing is to fetch the version of the dycore (after fetch of the package) with git of the working copy of the repo. If you set it to true, it would deduce the cosmo/dycore version from git, otherwise it will use the `tag` and `cosmo-dycore`. But after our discussions I think we agreed that we would get the version information simply from the spack spec of cosmo and add a ^cosmo-dycore to the spec with the same version. Additionally, we also learned that extracting and using information from git is not a good solution. When spack recovers a source package from the cache (tar file) it eliminates the .git folder. So in summary we should not replicate this behaviour in the final solution, and simply copy the version of cosmo from the spec into cosmo-dycore
`tag` and `cosmo-dycore`: were used in case we would trigger the build outside of spack, but since we opted for a spack custom command, the version information is already in the spec, so this is also not needed. For cosmo-dycore, see my comment above

2021-04-16 07:56 UTC, cosunae commented
Could you post an example yaml?

2021-04-16 12:04 UTC, Stagno commented
> some info about yaml:
> 
>     * `package: cosmo` -> just to identify the package, in case these yamls would end up in a workflows out of the repo. But we if aim putting it in the repo (in order to associate it with the tag) this is probably not needed.
> 
>     * `version_from_git: "false"` -> this was a first attempt to solve the problem of associating the dycore version with cosmo version. What this was doing is to fetch the version of the dycore (after fetch of the package) with git of the working copy of the repo. If you set it to true, it would deduce the cosmo/dycore version from git, otherwise it will use the `tag` and `cosmo-dycore`. But after our discussions I think we agreed that we would get the version information simply from the spack spec of cosmo and add a ^cosmo-dycore to the spec with the same version. Additionally, we also learned that extracting and using information from git is not a good solution. When spack recovers a source package from the cache (tar file) it eliminates the .git folder. So in summary we should not replicate this behaviour in the final solution, and simply copy the version of cosmo from the spec into cosmo-dycore
> 
>     * `tag` and `cosmo-dycore`: were used in case we would trigger the build outside of spack, but since we opted for a spack custom command, the version information is already in the spec, so this is also not needed. For cosmo-dycore, see my comment above

Thank you for the explanation, now I understand.
This means that when re-implementing `depinstallcosmo` with this approach, we'd take both the cosmo and the cosmo-dycore versions from the serialized `spec.yaml` and inject them (in the same way we do it for the other dependencies) in the spec to be installed, correct?

2021-04-16 16:07 UTC, BenWeber42 requested changes
Unfortuantely, I reviewed quite a few things that aren't part of this PR due to the formatting changes. I thought I'll put the comments here anyways, but it's not really part of the PR.

Nevertheless, I think we can improve things by using the `Spec.{from_yaml,to_dict,from_dict}` methods and just merging the dicts.

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    args.spec.append("^cosmo-dycore@dev-build")
Why do we need this?

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    deps_serialized_dict = dict((spec.name, spec) for spec in spec_list[1:])
Use `Spec.from_yaml`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/spack/spec.py#L2113-L2124

Once you have a spec, convert to dict by using `Spec.to_dict`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/spack/spec.py#L1684-L1753

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    # TODO: should we also take the cosmo version from the serialized yaml?
Once you have dicts for both the user defined spec (from command line `args.spec`) and the _defaults spec_ (from `./cosmo/ACC/spec.yaml`), you want to merge the two dicts recursively so that the user defined spec overwrite the _defaults spec_ in case of collisions.

For this I would write a simple recursive function. Technically, spack already contains such functionality for yaml config files (different scopes shadow themselves this way), but I don't know how to access the functionality and whether it really does what we want (it'll append lists to each other instead of overwriting, not sure if this is relevant to us).

Then convert the resulting dict back to a spec `Spec.from_dict`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/spack/spec.py#L2083-L2111

This final spec is the one we want to concretize (before the merge, we should only work with abstract specs).

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +            shutil.rmtree(source_path + "/spack-build")
We shouldn't hard code the colors and instead use the appropriate methos from `llnl.util.tty`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/llnl/util/tty/__init__.py#L156-L239

Not sure which color this is, maybe `msg`?

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        print("\033[92m" + "==> " + "\033[0m" + "cosmo: Serializing data")
Hardcoded terminal colors. Use `lllnl.util.tty`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/llnl/util/tty/__init__.py#L156-L239

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +                "\033[92m" + "==> " + "\033[0m" + "cosmo-dycore: Launching dycore tests"
Hardcoded terminal color: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/llnl/util/tty/__init__.py#L156-L239

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +import ruamel.yaml as yaml
```suggestion
from ruamel import yaml
```
minor python issue, but I think we can remove this import anyways, since we can use `Spec.from_yaml`...

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +            shutil.rmtree(source_path + "/spack-build")
ah wait, this is just formatting, so was there before. Hmm, well I guess it's up to you whether you want to change this :sweat_smile:

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        )
hmm, this was there before, but I think we should be able to use `Spec.get_dependency('cosmo-dycore')`: https://github.com/spack/spack/blob/5d88f439f34108b9b474dd495139e9c0b60c7336/lib/spack/spack/spec.py#L1139-L1143

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        print("Dycore full spec", dycore_spec)  # debug?
Yea, looks like a debug print. Otherwise we should probably use `tty.msg` or `tty.info`.

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +            )
Strange, we don't check the status code and also don't capture output :thinking:

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        )
again, no checks...

2021-04-16 16:07 UTC, BenWeber42 commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        )
again, no checks...

2021-04-22 13:10 UTC, Stagno commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    args.spec.append("^cosmo-dycore@dev-build")
The previous approach also forced selecting the `dev-build` version for the dycore when devbuilding `cosmo`.
I think the reason is to not have installation conflicts with a possibly already installed `cosmo-dycore@<some-version>`, i.e. `dev-build` is reserved for dev-builds, which just overwrite each other.

2021-04-23 10:09 UTC, Stagno commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    deps_serialized_dict = dict((spec.name, spec) for spec in spec_list[1:])
`Spec.from_yaml` returns only the root Spec object (i.e. cosmo), I need all but the root here instead.

2021-04-23 10:13 UTC, Stagno commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +    # TODO: should we also take the cosmo version from the serialized yaml?
I tried this approach in my first attempts. If I recall correctly, converting the spec that comes from the user to a dict makes it loose info about `cosmo-dycore` (which is a dependency that's declared in a particular way in cosmo's `package.py` and the conversion to dictionary is apparently not compatible with that approach).

2021-04-23 10:16 UTC, Stagno commented on tools/spack-scripting/scripting/cmd/devbuildcosmo.py
> +        print("Dycore full spec", dycore_spec)  # debug?
Removing it

2021-04-27 09:27 UTC, jonasjucker commented
@Stagno Is it possible to change cosunae:depinstall into spack:mch, otherwise I find it hard to distinguish what will change with this PR in the end.

2021-04-27 10:18 UTC, Stagno commented
> @Stagno Is it possible to change cosunae:depinstall into spack-mch:master, otherwise I find it hard to distinguish what will change with this PR in the end.

Sure, will switch now. Note also that unfortunately vscode ran the formatter against my will, so there will be formatting changes in `devbuildcosmo.py` to be ignored.

2021-04-27 10:24 UTC, Stagno commented
@jonasjucker had to create another PR on upstream: https://github.com/MeteoSwiss-APN/spack-mch/pull/213/files

2021-05-04 15:18 UTC, merged